name: Create and publish App
on:
  push:
    paths:
      - "app/**"
    branches:
      - master
    tags: v*.*.*
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/safepath-as/greentechsee-ksu-2025/app

jobs:
  build-and-push-app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}
          tags: |
            type=raw,value=dev
            type=sha
            type=semver,pattern={{version}}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push App
        uses: docker/build-push-action@v6
        with:
          context: app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            version=${{ github.ref_type == 'tag' && steps.meta.outputs.version || github.sha }}
