name: Run tests
on:
  push:
    paths:
      - "app/**"
    branches:
      - master
    tags: v*.*.*
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/safepath-as/greentechsee-ksu-2025/app

jobs:
  build-and-push-app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run tests
        run: pnpm test
